version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#    volumes:
#      - save_db:/var/lib/postgresql/data
    ports:
      - "5431:5432"



  spring-app:
    image: heavymetal-app:latest
    ports:
      - "7777:7777"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  save_db:
    driver: local
    driver_opts:
      type: none
      device: /var/lib/postgresql/data
      o: bind

