GET http://localhost:7777/api/subscription
Content-Type: application/json

###
GET http://localhost:7777/api/subscription/603d946a-1813-4680-bca2-3c9101a62c0d
Content-Type: application/json

###
DELETE http://localhost:7777/api/subscription/a4cfc27c-eb23-4903-819b-a2475fe0540b
Content-Type: application/json

###

POST http://localhost:7777/api/subscription
Content-Type: application/json

{
  "name": "Безлимит 2 месяца",
  "countVisits": "UNLIMITED_TWO",
  "price": 4000,
  "actionTime": 62
}

###
PUT http://localhost:7777/api/subscription
Content-Type: application/json

{
  "id": "a4cfc27c-eb23-4903-819b-a2475fe0540b",
  "name": "2",
  "countVisits": "EIGHT",
  "price": 2800,
  "actionTime": 30
}